"""Update User and Add Avatar models

Revision ID: f263b7fc3dec
Revises: ffdc0a98111c
Create Date: 2025-01-16 12:08:38.507584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f263b7fc3dec'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(), nullable=False, server_default='FirstName'))
        batch_op.add_column(sa.Column('last_name', sa.String(), nullable=False, server_default='LastName'))
        batch_op.add_column(sa.Column('tier', sa.String(), nullable=False, server_default='Basic'))
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=False, server_default=sa.sql.expression.false()))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('first_name', server_default=None)
        batch_op.alter_column('last_name', server_default=None)
        batch_op.alter_column('tier', server_default=None)
        batch_op.alter_column('is_admin', server_default=None)
        batch_op.alter_column('created_at', server_default=None)
        batch_op.alter_column('updated_at', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('is_admin')
        batch_op.drop_column('tier')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###
